ci:
  autofix_commit_msg: "chore(pre-commit): autofix run"
  autoupdate_commit_msg: "chore(pre-commit): autoupdate hooks"
  # as of 7/1/26, esbenp.prettier-vscode installs prettier@3.7.4.
  # pinning the mirror ensures that the VS Code plugin and pre-commit are simpatico
  # another option would be to install node/prettier manually, as the VS Code plugin will honor it
  skip: [prettier]

# by default, install these hook types
# https://pre-commit.com/#top_level-default_install_hook_types
default_install_hook_types:
  - pre-commit
  - commit-msg

# by default, confine hooks to these git stages (except for hooks that specify their own stages)
# https://pre-commit.com/#top_level-default_stages
default_stages: [pre-commit]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ["--maxkb=1500"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        types:
          - python

  - repo: https://github.com/pycqa/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        types:
          - python

  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # this hook is frozen at 3.7.4. see ci configuration code comment above for more info
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.9.4
    hooks:
      - id: prettier
        types_or: [javascript, css]

  - repo: https://github.com/djlint/djLint
    rev: v1.40.3
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
