# pyup.io config file
# see https://pyup.io/docs/configuration/ for all available options

schedule: "every day"
update: False
requirements:
  - requirements.txt:
      update: all
  - server/requirements.txt:
      update: insecure
