name: benefits

services:
  client:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: benefits_client:latest
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: benefits_client:dev
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    depends_on:
      - server
      - postgres
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"
    volumes:
      - ./:/calitp/app

  docs:
    image: benefits_client:dev
    entrypoint: mkdocs
    command: serve --livereload --dev-addr "0.0.0.0:8001"
    ports:
      - "8001"
    volumes:
      - ./:/calitp/app

  server:
    image: ghcr.io/cal-itp/eligibility-server:main
    env_file: .devcontainer/server/.env.server
    ports:
      - "8000"
    volumes:
      - ./.devcontainer:/.devcontainer

  playwright:
    build:
      context: .
      dockerfile: tests/playwright/Dockerfile
    env_file: .env
    image: benefits_client:playwright
    volumes:
      - ./tests/playwright:/playwright
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ./run.sh

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -h 127.0.0.1
      interval: 5s

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT:-8081}:8081"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${DJANGO_DB_NAME}?sslmode=disable

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "${PGADMIN_PORT:-8082}:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=benefits-admin@calitp.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
  pgadmin_data:
    driver: local
