@baseUrl = {{$dotenv psta_init_enrollment_api_base_url}}
@authHeader = {{$dotenv psta_init_enrollment_api_authorization_header }}

###

GET {{baseUrl}}/api/FareCategories HTTP/1.1
Authorization: {{authHeader}}

###

GET {{baseUrl}}/api/SalesChannels
Authorization: {{authHeader}}

###

GET {{baseUrl}}/api/FareMedia?SaleschannelId=420
Authorization: {{authHeader}}

###

POST {{baseUrl}}/api/TransitAccounts
Authorization: {{authHeader}}
Content-Type: application/json

{
  "FareMediaId": "133713370",
  "PrintedNumber": "133713370",
  "FareMediaTypeId": 1727934,
  "SalesChannelId": 420,
}

###

GET {{baseUrl}}/api/TransitAccounts?FareMediaId=133713370
Authorization: {{authHeader}}

###

POST {{baseUrl}}/api/Cardholders
Authorization: {{authHeader}}
Content-Type: application/json

{
    "FareCategory": "7",
    "TransitAccountId": "17718",
    "FirstName": "Kim",
    "LastName": "Possible"
}

###

GET {{baseUrl}}/api/Cardholders/12002
Authorization: {{authHeader}}
