# Generated by Django 5.2.11 on 2026-02-26 22:39
# flake8: noqa

import uuid

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models

import benefits.core.models.common
import benefits.core.models.transit
import benefits.secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cdt_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityApiVerificationRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.SlugField(help_text="A human readable label, used as the display text in Admin.")),
                ("api_url", models.URLField(help_text="Fully qualified URL for an Eligibility API server.")),
                (
                    "api_auth_header",
                    models.CharField(help_text="The auth header to send in Eligibility API requests.", max_length=50),
                ),
                (
                    "api_auth_key_secret_name",
                    benefits.core.models.common.SecretNameField(
                        help_text="The name of a secret containing the value of the auth header to send in Eligibility API requests.",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "api_jwe_cek_enc",
                    models.CharField(
                        help_text="The JWE-compatible Content Encryption Key (CEK) key-length and mode to use in Eligibility API requests.",
                        max_length=50,
                    ),
                ),
                (
                    "api_jwe_encryption_alg",
                    models.CharField(
                        help_text="The JWE-compatible encryption algorithm to use in Eligibility API requests.", max_length=50
                    ),
                ),
                (
                    "api_jws_signing_alg",
                    models.CharField(
                        help_text="The JWS-compatible signing algorithm to use in Eligibility API requests.", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PemData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(help_text="Human description of the PEM data")),
                (
                    "text_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of a secret with data in utf-8 encoded PEM text format",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "remote_url",
                    models.TextField(blank=True, default="", help_text="Public URL hosting the utf-8 encoded PEM text"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransitProcessorConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("dev", "Development"), ("test", "Testing"), ("prod", "Production")],
                        help_text="A label to indicate which environment this configuration is for.",
                    ),
                ),
                ("label", models.TextField(blank=True, default="", help_text="A label for internal use.")),
                (
                    "portal_url",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The absolute base URL for the TransitProcessor's control portal, including https://.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentFlow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "system_name",
                    models.SlugField(
                        choices=[
                            ("calfresh", "Calfresh"),
                            ("courtesy_card", "Courtesy Card"),
                            ("medicare", "Medicare"),
                            ("senior", "Older Adult"),
                            ("mobility_pass", "Reduced Fare Mobility Id"),
                            ("veteran", "Veteran"),
                        ],
                        help_text="Primary internal system name for this EnrollmentFlow instance, e.g. in analytics and Eligibility API requests.",
                    ),
                ),
                (
                    "label",
                    models.TextField(
                        blank=True, default="", help_text="A human readable label, used as the display text in Admin."
                    ),
                ),
                (
                    "supported_enrollment_methods",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("digital", "Digital"), ("in_person", "In-person")],
                        default=["digital", "in_person"],
                        help_text="If the flow is supported by digital enrollment, in-person enrollment, or both",
                        max_length=50,
                    ),
                ),
                (
                    "sign_out_button_template",
                    models.TextField(blank=True, default="", help_text="Template that renders sign-out button"),
                ),
                (
                    "sign_out_link_template",
                    models.TextField(blank=True, default="", help_text="Template that renders sign-out link"),
                ),
                (
                    "supports_expiration",
                    models.BooleanField(default=False, help_text="Indicates if the enrollment expires or does not expire"),
                ),
                (
                    "expiration_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="If the enrollment supports expiration, number of days before the eligibility expires",
                        null=True,
                    ),
                ),
                (
                    "expiration_reenrollment_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="If the enrollment supports expiration, number of days preceding the expiration date during which a user can re-enroll in the eligibilty",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "api_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Eligibility API request details for this flow.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.eligibilityapiverificationrequest",
                    ),
                ),
                (
                    "claims_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The claims request details for this flow.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.claimsverificationrequest",
                    ),
                ),
                (
                    "oauth_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="The IdG connection details for this flow.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.identitygatewayconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="eligibilityapiverificationrequest",
            name="api_public_key",
            field=models.ForeignKey(
                help_text="The public key used to encrypt Eligibility API requests and to verify signed Eligibility API responses.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityapiverificationrequest",
            name="client_private_key",
            field=models.ForeignKey(
                default=None,
                help_text="Private key used to sign Eligibility API tokens created on behalf of the Benefits client.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityapiverificationrequest",
            name="client_public_key",
            field=models.ForeignKey(
                default=None,
                help_text="Public key corresponding to the Benefits client's private key, used by Eligibility Verification servers to encrypt responses.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.CreateModel(
            name="TransitAgency",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=False, help_text="Determines if this Agency is enabled for users")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}",
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.TextField(
                        default="", help_text="The user-facing short name for this agency. Often an uppercase acronym."
                    ),
                ),
                (
                    "long_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The user-facing long name for this agency. Often the short_name acronym, spelled out.",
                    ),
                ),
                (
                    "info_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of a website/page with more information about the agency's discounts",
                    ),
                ),
                ("phone", models.TextField(blank=True, default="", help_text="Agency customer support phone number")),
                (
                    "supported_card_schemes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("discover", "Discover"),
                            ("amex", "American Express"),
                        ],
                        default=["visa", "mastercard"],
                        help_text="The contactless card schemes this agency supports.",
                        max_length=29,
                    ),
                ),
                (
                    "sso_domain",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The email domain of users to automatically add to this agency's staff group upon login.",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="",
                        help_text="The transit agency's logo.",
                        upload_to=benefits.core.models.transit.agency_logo,
                    ),
                ),
                (
                    "customer_service_group",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="The group of users who are allowed to do in-person eligibility verification and enrollment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transit_agency",
                        to="auth.group",
                    ),
                ),
                (
                    "enrollment_flows",
                    models.ManyToManyField(
                        help_text="Select the enrollment flows this agency supports.", to="core.enrollmentflow"
                    ),
                ),
                (
                    "transit_processor_config",
                    models.ForeignKey(
                        default=None,
                        help_text="The transit processor configuration to use for enrollment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.transitprocessorconfig",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transit agencies",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enrollment_flow",
                    models.ForeignKey(
                        help_text="The enrollment flow that this group is for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.enrollmentflow",
                    ),
                ),
                (
                    "transit_agency",
                    models.ForeignKey(
                        help_text="The transit agency that this group is for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.transitagency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("enrollment_method", models.TextField(choices=[("digital", "digital"), ("in_person", "in_person")])),
                ("verified_by", models.TextField()),
                ("enrollment_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiration_datetime", models.DateTimeField(blank=True, null=True)),
                ("extra_claims", models.TextField(blank=True, default="")),
                ("enrollment_flow", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.enrollmentflow")),
                ("transit_agency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.transitagency")),
            ],
        ),
    ]
