# Generated by Django 5.2.11 on 2026-03-10 20:49

import multiselectfield.db.fields
from django.db import migrations, models


def update_digital_method(apps, schema_editor):
    """Update models that previously used EnrollmentMethods.DIGITAL with the new value."""
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")
    EnrollmentEvent = apps.get_model("core", "EnrollmentEvent")

    for flow in EnrollmentFlow.objects.all():
        original_methods = list(flow.supported_enrollment_methods)
        new_methods = []
        if "digital" in original_methods:
            new_methods.append("self_service")
        if "in_person" in original_methods:
            new_methods.append("in_person")
        flow.supported_enrollment_methods = new_methods
        flow.save()

    for event in EnrollmentEvent.objects.all():
        if event.enrollment_method == "digital":
            event.enrollment_method = "self_service"
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentevent",
            name="enrollment_method",
            field=models.TextField(choices=[("self_service", "self_service"), ("in_person", "in_person")]),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="supported_enrollment_methods",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("self_service", "Self-service"), ("in_person", "In-person")],
                default=["self_service", "in_person"],
                help_text="If the flow is supported by self-service enrollment, in-person enrollment, or both",
                max_length=50,
            ),
        ),
        migrations.RunPython(update_digital_method),
    ]
