# Generated by Django 5.2.11 on 2026-03-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="transit_processor_config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The transit processor configuration to use for enrollment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.transitprocessorconfig",
            ),
        ),
    ]
