# Generated by Django 5.0.2 on 2024-02-28 23:16

import benefits.core.models
import benefits.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprocessor",
            name="audience",
            field=models.TextField(default="audience"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentprocessor",
            name="client_id",
            field=models.TextField(default="client_id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentprocessor",
            name="client_secret_name",
            field=benefits.core.models.SecretNameField(
                default="client_secret_name", max_length=127, validators=[benefits.secrets.SecretNameValidator()]
            ),
            preserve_default=False,
        ),
    ]
