# Generated by Django 3.2.9 on 2021-12-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="navigation_title",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.i18ntext"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="pagenavigation",
            name="classes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
