# Generated by Django 5.2.11 on 2026-03-10 20:49

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentevent",
            name="enrollment_method",
            field=models.TextField(choices=[("self_service", "self_service"), ("in_person", "in_person")]),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="supported_enrollment_methods",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("self_service", "Self-service"), ("in_person", "In-person")],
                default=["self_service", "in_person"],
                help_text="If the flow is supported by self-service enrollment, in-person enrollment, or both",
                max_length=50,
            ),
        ),
    ]
