# Generated by Django 5.2.11 on 2026-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blank_transit_processor_config_transitagency"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitAgencyGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(help_text="A human readable label, used as the display text in Admin.")),
                (
                    "transit_agencies",
                    models.ManyToManyField(
                        help_text="Select the agencies that belong to this group.", to="core.transitagency"
                    ),
                ),
            ],
        ),
    ]
