# Generated by Django 5.0.2 on 2024-02-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paymentprocessor_audience_paymentprocessor_client_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="api_access_token_endpoint",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="api_access_token_request_key",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="api_access_token_request_val",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="client_cert",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="client_cert_private_key",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="client_cert_root_ca",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="customer_endpoint",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="customers_endpoint",
        ),
        migrations.RemoveField(
            model_name="paymentprocessor",
            name="group_endpoint",
        ),
    ]
