# Generated by Django 5.0.2 on 2024-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paymentprocessor_backoffice_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitytype",
            name="expiration_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eligibilitytype",
            name="expiration_reenrollment_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eligibilitytype",
            name="supports_expiration",
            field=models.BooleanField(default=False),
        ),
    ]
