# Generated by Django 5.0.3 on 2024-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_eligibilitytype_expiration"),
    ]

    # see https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data
    def set_initial_display_order(apps, schema_editor):
        EligibilityVerifier = apps.get_model("core", "EligibilityVerifier")
        for order, item in enumerate(EligibilityVerifier.objects.all(), 1):
            item.display_order = order
            item.save(update_fields=["display_order"])

    operations = [
        migrations.AlterModelOptions(
            name="eligibilityverifier",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="eligibilityverifier",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(set_initial_display_order, reverse_code=migrations.RunPython.noop),
    ]
