# Generated by Django 5.2.11 on 2026-05-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_enrollment_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentflow",
            name="system_name",
            field=models.SlugField(
                choices=[
                    ("calfresh", "Calfresh"),
                    ("courtesy_card", "Courtesy Card"),
                    ("medicare", "Medicare"),
                    ("senior", "Older Adult"),
                    ("mobility_pass", "Reduced Fare Mobility Id"),
                    ("veteran", "Veteran"),
                    ("agency_card", "Gctd Card"),
                ],
                help_text="Primary internal system name for this EnrollmentFlow instance, e.g. in analytics and Eligibility "
                "API requests.",
            ),
        ),
    ]
