# Generated by Django 5.0.3 on 2024-03-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_eligibilityverifier_display_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="help_template",
        ),
        migrations.AddField(
            model_name="eligibilityverifier",
            name="help_template",
            field=models.TextField(null=True),
        ),
    ]
