# Generated by Django 5.0.3 on 2024-03-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_move_help_template_to_eligibilityverifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authprovider",
            name="claim",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="authprovider",
            name="scope",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="authprovider",
            name="sign_out_button_template",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="authprovider",
            name="sign_out_link_template",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="api_auth_header",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="api_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="auth_provider",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.authprovider"
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="form_class",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="help_template",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="jwe_cek_enc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="jwe_encryption_alg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="jws_signing_alg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="public_key",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.pemdata"
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityverifier",
            name="start_template",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pemdata",
            name="remote_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
