# Generated by Django 5.2.17 on 2026-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="in_person_policy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The policy language used by transit agency staff to verify a user's eligibility in-person.",
            ),
        )
    ]
