# Generated by Django 5.0.3 on 2024-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_allow_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitytype",
            name="enrollment_index_template",
            field=models.TextField(default="enrollment/index.html"),
        ),
    ]
