# Generated by Django 5.2.17 on 2026-08-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentflow",
            name="system_name",
            field=models.SlugField(
                choices=[
                    ("calfresh", "Calfresh"),
                    ("courtesy_card", "Courtesy Card"),
                    ("gctd_card", "Gctd Card"),
                    ("medicare", "Medicare"),
                    ("metro_mobility_wallet", "Metro Mobility Wallet"),
                    ("senior", "Older Adult"),
                    ("mobility_pass", "Reduced Fare Mobility Id"),
                    ("scmetro_card", "Scmetro Card"),
                    ("veteran", "Veteran"),
                ],
                help_text=(
                    "Primary internal system name for this EnrollmentFlow instance, "
                    "e.g. in analytics and Eligibility API requests."
                ),
            ),
        ),
    ]
