# Generated by Django 5.0.3 on 2024-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_eligibilityverifier_unverified_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitytype",
            name="reenrollment_error_template",
            field=models.TextField(blank=True, null=True),
        ),
    ]
