# Generated by Django 5.2.17 on 2026-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentevent",
            name="enrollment_method",
            field=models.CharField(choices=[("self_service", "self_service"), ("in_person", "in_person")]),
        ),
        migrations.AlterField(
            model_name="enrollmentevent",
            name="extra_claims",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="enrollmentevent",
            name="verified_by",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="label",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin."
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="sign_out_button_template",
            field=models.CharField(blank=True, default="", help_text="Template that renders sign-out button"),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="sign_out_link_template",
            field=models.CharField(blank=True, default="", help_text="Template that renders sign-out link"),
        ),
        migrations.AlterField(
            model_name="pemdata",
            name="label",
            field=models.CharField(help_text="Human description of the PEM data"),
        ),
        migrations.AlterField(
            model_name="pemdata",
            name="remote_url",
            field=models.URLField(blank=True, default="", help_text="Public URL hosting the utf-8 encoded PEM text"),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="long_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The user-facing long name for this agency. Often the short_name acronym, spelled out.",
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="phone",
            field=models.CharField(blank=True, default="", help_text="Agency customer support phone number"),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="short_name",
            field=models.CharField(
                default="", help_text="The user-facing short name for this agency. Often an uppercase acronym."
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="sso_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The email domain of users to automatically add to this agency's staff group upon login.",
            ),
        ),
        migrations.AlterField(
            model_name="transitagencygroup",
            name="label",
            field=models.CharField(help_text="A human readable label, used as the display text in Admin."),
        ),
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="environment",
            field=models.CharField(
                choices=[("dev", "Development"), ("test", "Testing"), ("prod", "Production")],
                help_text="A label to indicate which environment this configuration is for.",
            ),
        ),
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="label",
            field=models.CharField(blank=True, default="", help_text="A label for internal use."),
        ),
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="portal_url",
            field=models.URLField(
                blank=True, default="", help_text="The absolute base URL for the TransitProcessor's control portal."
            ),
        ),
    ]
