# Generated by Django 5.2.17 on 2026-09-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="label",
            field=models.CharField(blank=True, default="", help_text="A label for internal use."),
        ),
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="portal_url",
            field=models.URLField(
                blank=True, default="", help_text="The absolute base URL for the TransitProcessor's control portal."
            ),
        ),
    ]
