# Generated by Django 5.2.17 on 2026-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_reassign_textfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_en",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_es",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_hy",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_ja",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_ko",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_ru",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_th",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_vi",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_zh_hans",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="label_zh_hant",
            field=models.CharField(
                blank=True, default="", help_text="A human readable label, used as the display text in Admin.", null=True
            ),
        ),
    ]
