# Generated by Django 5.0.3 on 2024-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_secret_name_field_blank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="enrollment_success_template",
        ),
        migrations.AddField(
            model_name="eligibilitytype",
            name="enrollment_success_template",
            field=models.TextField(default="enrollment/success.html"),
        ),
    ]
