# Generated by Django 5.0.6 on 2024-07-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_move_enrollment_success_template_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="merchant_id",
        ),
    ]
