# Generated by Django 5.0.7 on 2024-07-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_staff_group_edit_permissions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentProcessor",
            new_name="TransitProcessor",
        ),
    ]
