# Generated by Django 5.0.7 on 2024-07-31 22:41

from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_all_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def update_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    staff_group = Group.objects.get(name="Cal-ITP")

    Permission = apps.get_model("auth", "Permission")

    remove_permissions = ["Can view", "Can change", "Can add", "Can delete"]
    for remove_permission in remove_permissions:
        current_permission = Permission.objects.get(name=f"{remove_permission} payment processor")
        staff_group.permissions.remove(current_permission)
        current_permission.delete()

    add_permissions = ["Can view", "Can change"]
    for add_permission in add_permissions:
        new_permission = Permission.objects.get(name=f"{add_permission} transit processor")
        staff_group.permissions.add(new_permission)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_staff_group_edit_permissions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentProcessor",
            new_name="TransitProcessor",
        ),
        migrations.RenameField(
            model_name="transitagency",
            old_name="payment_processor",
            new_name="transit_processor",
        ),
        migrations.RunPython(create_all_permissions),
        migrations.RunPython(update_permissions),
    ]
