# Generated by Django 5.0.7 on 2024-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_eligibility_api_fields"),
    ]

    operations = [
        migrations.RenameField(model_name="transitagency", old_name="agency_id", new_name="eligibility_api_id"),
        migrations.RenameField(
            model_name="transitagency", old_name="jws_signing_alg", new_name="eligibility_api_jws_signing_alg"
        ),
        migrations.RenameField(model_name="transitagency", old_name="private_key", new_name="eligibility_api_private_key"),
        migrations.RenameField(model_name="transitagency", old_name="public_key", new_name="eligibility_api_public_key"),
    ]
