# Generated by Django 5.0.7 on 2024-08-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_refactor_idg_config_eligibilityverifier"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EligibilityVerifier",
            new_name="EnrollmentFlow",
        ),
        migrations.RenameField(
            model_name="transitagency",
            old_name="eligibility_verifiers",
            new_name="enrollment_flows",
        ),
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="active",
        ),
    ]
