# Generated by Django 5.0.7 on 2024-08-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0022_refactor_EligibilityType_EnrollmentFlow"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitagency",
            name="staff_group",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The group of users who can access this TransitAgency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.group",
            ),
        ),
    ]
