# Generated by Django 5.0.7 on 2024-08-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0023_transitagency_staff_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitagency",
            name="sso_domain",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The email domain of users to automatically add to this agency's staff group upon login.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="staff_group",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The group of users associated with this TransitAgency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transit_agency",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="transitagency",
            name="customer_service_group",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The group of users who are allowed to do in-person eligibility verification and enrollment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="auth.group",
            ),
        ),
    ]
