# Generated by Django 5.1 on 2024-09-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_enrollmentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="supported_methods",
            field=models.TextField(
                choices=[("digital", "digital"), ("in_person", "in_person")],
                default="",
                help_text="If the flow is supported by digital, in-person, or both",
            ),
        ),
    ]
