# Generated by Django 5.1 on 2024-09-19 20:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_enrollmentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="supported_enrollment_methods",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("digital", "Digital"), ("in_person", "In-person")],
                default=["digital", "in_person"],
                help_text="If the flow is supported by digital enrollment, in-person enrollment, or both",
                max_length=50,
            ),
        ),
    ]
