# Generated by Django 5.1.1 on 2024-09-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_enrollmentflow_supported_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="enrollment_flows",
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="transit_agency",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.transitagency"),
            preserve_default=False,
        ),
    ]
