# Generated by Django 5.1.1 on 2024-10-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_transitagency_enrollment_flows_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollmentflow",
            old_name="claims_claim",
            new_name="claims_eligibility_claim",
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="claims_extra_claims",
            field=models.TextField(blank=True, help_text="A space-separated list of any additional claims", null=True),
        ),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="claims_eligibility_claim",
            field=models.TextField(
                blank=True, help_text="The name of the claim that is used to verify eligibility", null=True
            ),
        ),
    ]
