# Generated by Django 5.1 on 2024-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_refactor_transitagency_enrollmentflow_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentflow",
            name="label",
            field=models.TextField(help_text="A human readable label, used as the display text in Admin.", null=True),
        ),
    ]
