# Generated by Django 5.1.2 on 2024-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_extra_claims"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentevent",
            name="extra_claims",
            field=models.TextField(blank=True, null=True),
        ),
    ]
