# Generated by Django 5.1.2 on 2024-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_enrollmentevent_extra_claims"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitagency",
            name="logo_large",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="The large version of the transit agency's logo.",
                null=True,
                upload_to="logo_large",
            ),
        ),
        migrations.AddField(
            model_name="transitagency",
            name="logo_small",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="The small version of the transit agency's logo.",
                null=True,
                upload_to="logo_small",
            ),
        ),
    ]
