# Generated by Django 5.1.2 on 2024-10-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_transitagency_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transitagency", old_name="eligibility_index_template", new_name="eligibility_index_template_override"
        ),
        migrations.RenameField(model_name="transitagency", old_name="index_template", new_name="index_template_override"),
        migrations.AlterField(
            model_name="transitagency",
            name="eligibility_index_template_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Override the default template used for this agency's eligibility landing page",
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="index_template_override",
            field=models.TextField(
                blank=True, default="", help_text="Override the default template used for this agency's landing page"
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="eligibility_api_id",
            field=models.TextField(
                blank=True, default="", help_text="The identifier for this agency used in Eligibility API calls.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="eligibility_api_jws_signing_alg",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The JWS-compatible signing algorithm used in Eligibility API calls.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="eligibility_api_private_key",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Private key used to sign Eligibility API tokens created on behalf of this Agency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="eligibility_api_public_key",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Public key corresponding to the agency's private key, used by Eligibility Verification servers to encrypt responses.",  # noqa: E501
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="slug",
            field=models.SlugField(
                help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}"
            ),
        ),
    ]
