# Generated by Django 5.1.4 on 2025-01-03 01:59

from django.db import migrations, models

import benefits.core.models.common
import benefits.secrets


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_optionalfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemdata",
            name="label",
            field=models.TextField(help_text="Human description of the PEM data"),
        ),
        migrations.AlterField(
            model_name="pemdata",
            name="remote_url",
            field=models.TextField(blank=True, default="", help_text="Public URL hosting the utf-8 encoded PEM text"),
        ),
        migrations.AlterField(
            model_name="pemdata",
            name="text_secret_name",
            field=benefits.core.models.common.SecretNameField(
                blank=True,
                default="",
                help_text="The name of a secret with data in utf-8 encoded PEM text format",
                max_length=127,
                validators=[benefits.secrets.SecretNameValidator()],
            ),
        ),
    ]
