# Generated by Django 5.1.3 on 2025-02-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_pemdata_helptext"),
    ]

    def set_index_context_key(apps, schema_editor):
        TransitAgency = apps.get_model("core", "TransitAgency")
        for agency in TransitAgency.objects.all():
            agency.index_context_key = agency.slug
            agency.save()

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="index_template_override",
        ),
        migrations.AddField(
            model_name="transitagency",
            name="index_context_key",
            field=models.TextField(
                blank=True,
                choices=[("cst", "Cst"), ("mst", "Mst"), ("nevco", "Nevco"), ("sacrt", "Sacrt"), ("sbmtd", "Sbmtd")],
                default="",
                help_text="The copy to use on this transit agency's index page.",
                verbose_name="Index copy",
            ),
        ),
        # populate the new field with the TransitAgency's slug
        migrations.RunPython(set_index_context_key, reverse_code=migrations.RunPython.noop),
    ]
