# Generated by Django 5.1.5 on 2025-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_pemdata_helptext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="index_template_override",
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="slug",
            field=models.SlugField(
                choices=[("cst", "cst"), ("mst", "mst"), ("nevco", "nevco"), ("sacrt", "sacrt"), ("sbmtd", "sbmtd")],
                help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}",
            ),
        ),
    ]
