# Generated by Django 5.1.5 on 2025-02-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_in_person_enrollmentflows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="eligibility_index_template_override",
        ),
    ]
