# Generated by Django 5.1.7 on 2025-03-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_transitagency_eligibility_index_template_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="eligibility_start_template_override",
        ),
    ]
