# Generated by Django 5.1.7 on 2025-03-19 20:07

import django.db.models.deletion
from django.db import migrations, models
from benefits.secrets import get_secret_by_name


def migrate_data_claimsprovider_to_idgconfig(apps, schema_editor):
    ClaimsProvider = apps.get_model("core", "ClaimsProvider")
    IdentityGatewayConfig = apps.get_model("cdt_identity", "IdentityGatewayConfig")

    for claims_provider in ClaimsProvider.objects.all():
        client_id = get_secret_by_name(claims_provider.client_id_secret_name)
        identity_gateway_config = IdentityGatewayConfig.objects.create(
            client_name=claims_provider.client_name,
            client_id=client_id,
            authority=claims_provider.authority,
            scheme=claims_provider.scheme,
        )
        identity_gateway_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cdt_identity", "0001_initial"),
        ("core", "0039_remove_enrollmentflow_help_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="oauth_config",
            field=models.ForeignKey(
                blank=True,
                help_text="The IdG connection details for this flow.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cdt_identity.identitygatewayconfig",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="sign_out_button_template",
            field=models.TextField(blank=True, default="", help_text="Template that renders sign-out button"),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="sign_out_link_template",
            field=models.TextField(blank=True, default="", help_text="Template that renders sign-out link"),
        ),
        migrations.RunPython(migrate_data_claimsprovider_to_idgconfig),
    ]
