# Generated by Django 5.1.7 on 2025-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_enrollmentflow_help_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="eligibility_unverified_template_override",
        ),
    ]
