# Generated by Django 5.1.7 on 2025-03-19 20:07

import django.db.models.deletion
from django.db import migrations, models

from benefits.secrets import get_secret_by_name


def migrate_data_claimsprovider_to_idgconfig(apps, schema_editor):
    ClaimsProvider = apps.get_model("core", "ClaimsProvider")
    IdentityGatewayConfig = apps.get_model("cdt_identity", "IdentityGatewayConfig")

    for claims_provider in ClaimsProvider.objects.all():
        client_id = get_secret_by_name(claims_provider.client_id_secret_name)
        identity_gateway_config = IdentityGatewayConfig.objects.create(
            client_name=claims_provider.client_name,
            client_id=client_id,
            authority=claims_provider.authority,
            scheme=claims_provider.scheme,
        )
        identity_gateway_config.save()


def migrate_data_enrollmentflow(apps, schema_editor):
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")
    IdentityGatewayConfig = apps.get_model("cdt_identity", "IdentityGatewayConfig")

    idg_systems = ["calfresh", "medicare", "senior", "veteran"]

    for flow in EnrollmentFlow.objects.all():
        if flow.system_name in idg_systems:
            flow.oauth_config = IdentityGatewayConfig.objects.get(client_name=flow.claims_provider.client_name)
            flow.sign_out_button_template = flow.claims_provider.sign_out_button_template
            flow.sign_out_link_template = flow.claims_provider.sign_out_link_template
            flow.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cdt_identity", "0001_initial"),
        ("core", "0040_remove_enrollmentflow_eligibility_unverified_template_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="oauth_config",
            field=models.ForeignKey(
                blank=True,
                help_text="The IdG connection details for this flow.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cdt_identity.identitygatewayconfig",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="sign_out_button_template",
            field=models.TextField(blank=True, default="", help_text="Template that renders sign-out button"),
        ),
        migrations.AddField(
            model_name="enrollmentflow",
            name="sign_out_link_template",
            field=models.TextField(blank=True, default="", help_text="Template that renders sign-out link"),
        ),
        migrations.RunPython(migrate_data_claimsprovider_to_idgconfig),
        migrations.RunPython(migrate_data_enrollmentflow),
        migrations.AlterField(
            model_name="enrollmentflow",
            name="claims_scheme_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "The authentication scheme to use (Optional). If blank, "
                    "defaults to the value in Identity gateway configs"
                ),
                verbose_name="Claims scheme",
            ),
        ),
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="claims_provider",
        ),
        migrations.DeleteModel(
            name="ClaimsProvider",
        ),
    ]
