# Generated by Django 5.1.7 on 2025-03-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_enrollmentflow_eligibility_unverified_template_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="enrollment_success_template_override",
        ),
    ]
