# Generated by Django 5.1.7 on 2025-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_oauth_refactor_identitygatewayconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="enrollment_success_template_override",
        ),
    ]
