# Generated by Django 5.1.7 on 2025-03-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdt_identity", "0001_initial"),
        ("core", "0042_remove_enrollmentflow_enrollment_success_template_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentflow",
            name="claims_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The claims request details for this flow.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cdt_identity.claimsverificationrequest",
            ),
        ),
    ]
