# Generated by Django 5.1.7 on 2025-04-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_enrollmentflow_claims_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="enrollment_index_template_override",
        ),
    ]
