# Generated by Django 5.1.7 on 2025-04-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_enrollmentflow_enrollment_index_template_override"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transitagency",
            options={"verbose_name_plural": "transit agencies"},
        ),
    ]
