# Generated by Django 5.1.7 on 2025-04-18 13:52

from django.db import migrations, models

import benefits.core.models.common
import benefits.secrets


def migrate_littlepay_config(apps, schema_editor):
    TransitAgency = apps.get_model("core", "TransitAgency")
    LittlepayConfig = apps.get_model("core", "LittlepayConfig")

    for agency in TransitAgency.objects.all():
        agency_slug = agency.slug
        audience = agency.transit_processor_audience
        client_id = agency.transit_processor_client_id
        client_secret_name = agency.transit_processor_client_secret_name

        littlepay_config = LittlepayConfig.objects.create(
            agency_slug=agency_slug, audience=audience, client_id=client_id, client_secret_name=client_secret_name
        )
        littlepay_config.save()

        agency.littlepay_config = littlepay_config
        agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_transitagency_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LittlepayConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("qa", "QA"), ("prod", "Production")],
                        help_text="A label to indicate which environment this configuration is for.",
                    ),
                ),
                (
                    "agency_slug",
                    models.SlugField(
                        choices=[("cst", "cst"), ("mst", "mst"), ("nevco", "nevco"), ("sacrt", "sacrt"), ("sbmtd", "sbmtd")],
                        help_text="A label to indicate which agency this configuration is for. Note: the field that controls which configuration an agency actually uses is on the TransitAgency model.",  # noqa
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's audience value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's client_id value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing this agency's client_secret value used to access the TransitProcessor's API.",  # noqa
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transitagency",
            name="littlepay_config",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The Littlepay configuration used by this agency for enrollment.",
                null=True,
                on_delete=models.deletion.PROTECT,
                to="core.littlepayconfig",
            ),
        ),
        migrations.RunPython(migrate_littlepay_config),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_audience",
        ),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_client_id",
        ),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_client_secret_name",
        ),
    ]
