# Generated by Django 5.1.7 on 2025-04-17 00:40

import benefits.core.models.common
import benefits.secrets
import django.db.models.deletion
from django.db import migrations, models


def migrate_credentials(apps, schema_editor):
    TransitAgency = apps.get_model("core", "TransitAgency")
    LittlepayCredentials = apps.get_model("core", "LittlepayCredentials")

    for agency in TransitAgency.objects.all():
        audience = agency.transit_processor_audience
        client_id = agency.transit_processor_client_id
        client_secret_name = agency.transit_processor_client_secret_name

        littlepay_credentials = LittlepayCredentials.objects.create(
            audience=audience, client_id=client_id, client_secret_name=client_secret_name
        )
        littlepay_credentials.save()

        agency.littlepay_credentials = littlepay_credentials
        agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_transitagency_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LittlepayCredentials",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("qa", "QA"), ("prod", "Production")],
                        help_text="Indicates which API environment these credentials are for.",
                    ),
                ),
                (
                    "agency_slug",
                    models.SlugField(
                        choices=[("cst", "cst"), ("mst", "mst"), ("nevco", "nevco"), ("sacrt", "sacrt"), ("sbmtd", "sbmtd")],
                        help_text="Indicates which agency these credentials are for.",
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The audience value used to access the Littlepay API.",
                    ),
                ),
                (
                    "client_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The client_id value used to access the Littlepay API.",
                    ),
                ),
                (
                    "client_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing the client_secret value used to access the Littlepay API.",  # noqa
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
            ],
            options={"verbose_name": "Littlepay credential"},
        ),
        migrations.AddField(
            model_name="transitagency",
            name="littlepay_credentials",
            field=models.OneToOneField(
                blank=True,
                help_text="API credentials to be used with this agency's Littlepay TransitProcessor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.LittlepayCredentials",
            ),
        ),
        migrations.RunPython(migrate_credentials),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_audience",
        ),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_client_id",
        ),
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor_client_secret_name",
        ),
    ]
