# Generated by Django 5.1.7 on 2025-04-21 16:28

import benefits.core.models.common
import benefits.secrets
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_littlepayconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchioConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("qa", "QA"), ("prod", "Production")],
                        help_text="A label to indicate which environment this configuration is for.",
                    ),
                ),
                (
                    "api_key",
                    models.TextField(blank=True, default="", help_text="The API key used to access the Switchio API."),
                ),
                (
                    "api_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing the api_secret value used to access the Switchio API.",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "ca_certificate",
                    models.ForeignKey(
                        help_text="The CA certificate chain for accessing the Switchio API.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        help_text="The client certificate for accessing the Switchio API.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
            ],
        ),
    ]
