# Generated by Django 5.1.7 on 2025-04-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_switchioconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitprocessor",
            name="card_tokenize_env",
        ),
        migrations.RemoveField(
            model_name="transitprocessor",
            name="card_tokenize_func",
        ),
        migrations.RemoveField(
            model_name="transitprocessor",
            name="card_tokenize_url",
        ),
    ]
