# Generated by Django 5.1.7 on 2025-05-05 19:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_littlepay_config(apps, schema_editor):
    TransitAgency = apps.get_model("core", "TransitAgency")
    core_LittlepayConfig = apps.get_model("core", "LittlepayConfig")
    enrollment_littlepay_LittlepayConfig = apps.get_model("enrollment_littlepay", "LittlepayConfig")

    for old_config in core_LittlepayConfig.objects.all():

        new_config = enrollment_littlepay_LittlepayConfig.objects.create(
            environment=old_config.environment,
            agency_slug=old_config.agency_slug,
            audience=old_config.audience,
            client_id=old_config.client_id,
            client_secret_name=old_config.client_secret_name,
        )
        new_config.save()

        referencing_transit_agency = TransitAgency.objects.filter(littlepay_config__id=old_config.id).first()

        if referencing_transit_agency:
            referencing_transit_agency.littlepay_config = new_config
            referencing_transit_agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_remove_card_tokenize_fields"),
        ("enrollment_littlepay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="littlepay_config",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The Littlepay configuration used by this agency for enrollment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enrollment_littlepay.littlepayconfig",
            ),
        ),
        migrations.RunPython(migrate_littlepay_config),
        migrations.DeleteModel(
            name="LittlepayConfig",
        ),
    ]
