# Generated by Django 5.1.7 on 2025-05-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_transitagency_littlepay_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switchioconfig",
            name="ca_certificate",
        ),
        migrations.RemoveField(
            model_name="switchioconfig",
            name="client_certificate",
        ),
        migrations.RemoveField(
            model_name="switchioconfig",
            name="private_key",
        ),
    ]
