# Generated by Django 5.1.7 on 2025-05-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_switchioconfig_ca_certificate_and_more"),
        ("enrollment_switchio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="switchio_config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The Switchio configuration used by this agency for enrollment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enrollment_switchio.switchioconfig",
            ),
        ),
        migrations.DeleteModel(
            name="SwitchioConfig",
        ),
    ]
