# Generated by Django 5.1.7 on 2025-05-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_transitagency_switchio_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitprocessor",
            name="api_base_url",
        ),
    ]
