# Generated by Django 5.1.7 on 2025-07-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_transitprocessor_api_base_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enrollment_flow",
                    models.OneToOneField(
                        help_text="The enrollment flow that this group is for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.enrollmentflow",
                    ),
                ),
            ],
        ),
    ]
