# Generated by Django 5.1.7 on 2025-07-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_transitprocessor_api_base_url"),
        ("enrollment_switchio", "0002_switchioconfig_enrollment_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="switchio_config",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="The Switchio configuration used by this agency for enrollment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enrollment_switchio.switchioconfig",
            ),
        ),
    ]
