# Generated by Django 5.1.7 on 2025-07-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0052_enrollmentgroup"), ("enrollment_littlepay", "0002_littlepaygroup")]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="group_id",
        ),
    ]
