# Generated by Django 5.1.7 on 2025-07-11 20:01

from uuid import UUID
from django.db import migrations


def migrate_littlepay_group_ids(apps, schema_editor):
    LittlepayGroup = apps.get_model("enrollment_littlepay", "LittlepayGroup")
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")

    for flow in EnrollmentFlow.objects.all():
        group_id = flow.group_id
        if group_id:
            try:
                UUID(group_id, version=4)
            except ValueError as e:
                raise ValueError(f"Invalid group_id {group_id} on flow {flow}") from e

            littlepay_group = LittlepayGroup.objects.create(group_id=group_id, enrollment_flow=flow)
            littlepay_group.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0052_enrollmentgroup"), ("enrollment_littlepay", "0002_littlepaygroup")]

    operations = [
        migrations.RunPython(migrate_littlepay_group_ids),
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="group_id",
        ),
    ]
