# Generated by Django 5.1.7 on 2025-07-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_remove_enrollmentflow_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitProcessorConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("qa", "QA"), ("prod", "Production")],
                        help_text="A label to indicate which environment this configuration is for.",
                    ),
                ),
                (
                    "agency_slug",
                    models.SlugField(
                        choices=[("cst", "cst"), ("mst", "mst"), ("nevco", "nevco"), ("sacrt", "sacrt"), ("sbmtd", "sbmtd")],
                        help_text="A label to indicate which agency this configuration is for.",
                    ),
                ),
                (
                    "transit_agency",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="The transit agency that uses this configuration.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.transitagency",
                    ),
                ),
            ],
        ),
    ]
