# Generated by Django 5.1.7 on 2025-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_transitprocessorconfig"),
        ("enrollment_littlepay", "0004_littlepayconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="littlepay_config",
        ),
    ]
