# Generated by Django 5.1.7 on 2025-07-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_remove_transitagency_littlepay_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="switchio_config",
        ),
    ]
