# Generated by Django 5.1.7 on 2025-07-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_transitagency_switchio_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitprocessorconfig",
            name="agency_slug",
        ),
    ]
