# Generated by Django 5.1.7 on 2025-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_remove_transitprocessorconfig_agency_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("cst", "cst"),
                    ("mst", "mst"),
                    ("nevco", "nevco"),
                    ("sacrt", "sacrt"),
                    ("sbmtd", "sbmtd"),
                    ("ventura", "ventura"),
                ],
                help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}",
            ),
        ),
    ]
