# Generated by Django 5.1.7 on 2025-09-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_vctc_transitagency_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="eligibility_form_class",
        ),
    ]
