# Generated by Django 5.1.7 on 2025-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_transitagency_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="transit_processor",
        ),
        migrations.AddField(
            model_name="transitprocessorconfig",
            name="portal_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The absolute base URL for the TransitProcessor's control portal, including https://.",
            ),
        ),
        migrations.DeleteModel(
            name="TransitProcessor",
        ),
    ]
