# Generated by Django 5.1.7 on 2025-09-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_remove_transitprocessor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="reenrollment_error_template",
        ),
    ]
