# Generated by Django 5.1.7 on 2025-09-15 20:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_remove_enrollmentflow_reenrollment_error_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitagency",
            name="supported_card_schemes",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("discover", "Discover"),
                    ("amex", "American Express"),
                ],
                default=["visa", "mastercard"],
                help_text="The contactless card schemes this agency supports.",
                max_length=29,
            ),
        ),
    ]
