# Generated by Django 5.2.7 on 2025-10-30 15:22

from django.db import migrations, models

import benefits.core.models.transit


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_transitagency_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitagency",
            name="logo_large",
        ),
        migrations.RenameField(
            model_name="transitagency",
            old_name="logo_small",
            new_name="logo",
        ),
        migrations.AlterField(
            model_name="transitagency",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="The transit agency's logo.",
                upload_to=benefits.core.models.transit.agency_logo,
            ),
        ),
    ]
