# Generated by Django 5.2.7 on 2025-11-15 02:20

from django.db import migrations


def remove_stale_permissions(apps, schema_editor):
    """
    Finds all permissions now defined explicitly in code and removes them
    from all users and groups.
    """
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")

    APP_LABELS = ["core", "enrollment_littlepay"]

    # find all permissions for the apps listed above
    content_types = ContentType.objects.filter(app_label__in=APP_LABELS)
    permissions_to_clear = Permission.objects.filter(content_type__in=content_types)

    # clear them from all Groups
    for group in Group.objects.prefetch_related("permissions"):
        group.permissions.remove(*permissions_to_clear)

    # clear them from all Users
    for user in User.objects.prefetch_related("user_permissions"):
        user.user_permissions.remove(*permissions_to_clear)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_consolidate_transitagency_logo_columns"),
        ("enrollment_littlepay", "0005_delete_oldlittlepayconfig"),
        # Also depend on auth and contenttypes
        ("auth", "__latest__"),
        ("contenttypes", "__latest__"),
    ]

    operations = [migrations.RunPython(remove_stale_permissions)]
