# Generated by Django 5.2.7 on 2026-01-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_remove_transitagency_staff_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentflow",
            name="selection_label_template_override",
        ),
    ]
