# Generated by Django 5.2.7 on 2026-01-15 20:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_eligibility_api_config_data(apps, schema_editor):
    EligibilityApiConfig = apps.get_model("core", "EligibilityApiConfig")
    EligibilityApiVerificationRequest = apps.get_model("core", "EligibilityApiVerificationRequest")

    eligibility_api_config = EligibilityApiConfig.objects.first()

    for request in EligibilityApiVerificationRequest.objects.all():
        request.client_private_key = eligibility_api_config.api_private_key
        request.client_public_key = eligibility_api_config.api_public_key
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_remove_enrollmentflow_selection_label_template_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilityapiverificationrequest",
            name="client_private_key",
            field=models.ForeignKey(
                default=None,
                help_text="Private key used to sign Eligibility API tokens created on behalf of the Benefits client.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityapiverificationrequest",
            name="client_public_key",
            field=models.ForeignKey(
                default=None,
                help_text=(
                    "Public key corresponding to the Benefits client's private key, used by "
                    "Eligibility Verification servers to encrypt responses."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.pemdata",
            ),
        ),
        migrations.RunPython(migrate_eligibility_api_config_data),
        migrations.RemoveField(
            model_name="eligibilityapiconfig",
            name="api_private_key",
        ),
        migrations.RemoveField(
            model_name="eligibilityapiconfig",
            name="api_public_key",
        ),
        migrations.RemoveField(
            model_name="eligibilityapiconfig",
            name="api_id",
        ),
        migrations.RemoveField(
            model_name="transitagency",
            name="eligibility_api_config",
        ),
        migrations.DeleteModel(
            name="EligibilityApiConfig",
        ),
    ]
