# Generated by Django 5.2.7 on 2026-01-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_move_fields_from_eligapiconfig_to_eligapiverificationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("cst", "cst"),
                    ("mst", "mst"),
                    ("edcta", "edcta"),
                    ("nevco", "nevco"),
                    ("raba", "raba"),
                    ("roseville", "roseville"),
                    ("sacrt", "sacrt"),
                    ("sbmtd", "sbmtd"),
                    ("slorta", "slorta"),
                    ("vctc", "vctc"),
                ],
                help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}",
            ),
        ),
    ]
