# Generated by Django 5.2.7 on 2026-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_move_fields_from_eligapiconfig_to_eligapiverificationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="environment",
            field=models.TextField(
                choices=[("qa", "QA"), ("acc", "Acceptance"), ("prod", "Production")],
                help_text="A label to indicate which environment this configuration is for.",
            ),
        ),
    ]
