# Generated by Django 5.2.7 on 2026-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_add_roseville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitprocessorconfig",
            name="environment",
            field=models.TextField(
                choices=[("dev", "Development"), ("test", "Testing"), ("prod", "Production")],
                help_text="A label to indicate which environment this configuration is for.",
            ),
        ),
    ]
