# Generated by Django 5.2.11 on 2026-02-11 21:02

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")

    for flow in EnrollmentFlow.objects.all():
        if flow.system_name == "agency_card":
            flow.system_name = "courtesy_card"
        flow.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_update_env_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentflow",
            name="system_name",
            field=models.SlugField(
                choices=[
                    ("calfresh", "Calfresh"),
                    ("courtesy_card", "Courtesy Card"),
                    ("medicare", "Medicare"),
                    ("senior", "Older Adult"),
                    ("mobility_pass", "Reduced Fare Mobility Id"),
                    ("veteran", "Veteran"),
                ],
                help_text="Primary internal system name for this EnrollmentFlow instance, e.g. in analytics and Eligibility API requests.",  # noqa
            ),
        ),
        migrations.RunPython(migrate_data),
    ]
