# Generated by Django 5.2.11 on 2026-02-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_rm_agency_card_system_name_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitagency",
            name="slug",
            field=models.SlugField(
                help_text="Used for URL navigation for this agency, e.g. the agency homepage url is /{slug}", unique=True
            ),
        ),
    ]
