# Generated by Django 5.2.11 on 2026-02-20 20:25

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    """
    Set `TransitProcessorConfig.label` using its `transit_agency.slug`.
    Set `TransitAgency.transit_processor_config` using the existing `TransitProcessorConfig` that references the agency.
    """
    TransitProcessorConfig = apps.get_model("core", "TransitProcessorConfig")

    transit_processor_configs = TransitProcessorConfig.objects.all()

    for config in transit_processor_configs:
        config.label = config.transit_agency.slug
        config.save()

        agency = config.transit_agency
        agency.transit_processor_config = config
        agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_rm_agency_card_system_name_choice")
        # ("core", "0076_alter_transitagency_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitprocessorconfig",
            name="label",
            field=models.TextField(blank=True, default="", help_text="A label for internal use."),
        ),
        migrations.AddField(
            model_name="transitagency",
            name="transit_processor_config",
            field=models.ForeignKey(
                default=None,
                help_text="The transit processor configuration to use for enrollment.",
                null=True,
                on_delete=models.deletion.PROTECT,
                to="core.transitprocessorconfig",
            ),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name="transitprocessorconfig",
            name="transit_agency",
        ),
    ]
