# Generated by Django 5.2.11 on 2026-02-18 21:20

from pprint import pprint

import django.db.models.deletion
from django.db import migrations, models

from benefits.core.models.enrollment import SystemName


def select_global_flows(apps):
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")
    results = {}

    for system_name in SystemName:
        flow = EnrollmentFlow.objects.filter(system_name=system_name).first()
        results |= {system_name: flow}

    print("\n")
    pprint(results)
    return results


def migrate_enrollmentevent_data(apps, global_flows):
    EnrollmentEvent = apps.get_model("core", "EnrollmentEvent")

    # print(f"EnrollmentEvent objects before modifying: {EnrollmentEvent.objects.count()}")
    # print(f"first EnrollmentEvent id: {EnrollmentEvent.objects.first().id}")
    # print(f"last EnrollmentEvent id: {EnrollmentEvent.objects.last().id}")
    # print(
    #     f"EnrollmentEvent e6f2fb76b51e47da8ecb3788d603954f found? "
    #     f"{EnrollmentEvent.objects.filter(pk="e6f2fb76b51e47da8ecb3788d603954f").count()}"
    # )

    for event in EnrollmentEvent.objects.all():
        # print(event.id)
        existing_flow = event.enrollment_flow
        global_flow = global_flows[existing_flow.system_name]
        if event.id == "e6f2fb76b51e47da8ecb3788d603954f":
            print(existing_flow)
            print(global_flow)
        if existing_flow != global_flow:
            event.enrollment_flow = global_flow
            event.save()
            # event.save(update_fields=["enrollment_flow"])

        # print(f"EnrollmentEvent objects after modifying: {EnrollmentEvent.objects.count()}")
        # print(f"first EnrollmentEvent id: {EnrollmentEvent.objects.first().id}")
        # print(f"last EnrollmentEvent id: {EnrollmentEvent.objects.last().id}")
        # print(
        #     f"EnrollmentEvent e6f2fb76b51e47da8ecb3788d603954f found? "
        #     f"{EnrollmentEvent.objects.filter(pk="e6f2fb76b51e47da8ecb3788d603954f").count()}"
        # )

        # for event in EnrollmentEvent.objects.all():
        #     print(
        #         event.id,
        #         event.enrollment_method,
        #         event.verified_by,
        #         event.enrollment_datetime,
        #         event.enrollment_flow,
        #         event.transit_agency,
        #     )


def migrate_enrollmentgroup_data(apps, global_flows):
    EnrollmentGroup = apps.get_model("core", "EnrollmentGroup")

    for group in EnrollmentGroup.objects.all():
        existing_flow = group.enrollment_flow
        group.enrollment_flow = global_flows[existing_flow.system_name]
        group.transit_agency = existing_flow.transit_agency
        group.save(update_fields=["enrollment_flow", "transit_agency"])


def migrate_data(apps, schema_editor):
    """Populate each TransitAgency's enrollment_flows field and delete flows that are no longer needed

    In addition to the above, this function is used to orchestrate other data migration functions (defined above)
    so that we guarantee that the chosen global flows are consistent.
    """

    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")
    TransitAgency = apps.get_model("core", "TransitAgency")
    global_flows = select_global_flows(apps)

    migrate_enrollmentgroup_data(apps, global_flows)
    migrate_enrollmentevent_data(apps, global_flows)

    for agency in TransitAgency.objects.all():
        existing_flows = EnrollmentFlow.objects.filter(transit_agency=agency)

        for existing_flow in existing_flows:
            global_flow = global_flows[existing_flow.system_name]
            agency.enrollment_flows.add(global_flow)

            if existing_flow != global_flow:
                existing_flow.delete()

        agency.save()
        print(f"{agency.short_name}: {agency.enrollment_flows.count()} flows")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_alter_agency_to_config_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitagency",
            name="enrollment_flows",
            field=models.ManyToManyField(
                help_text="Select the enrollment flows this agency supports.",
                to="core.enrollmentflow",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentgroup",
            name="transit_agency",
            field=models.ForeignKey(
                default=1,
                help_text="The transit agency that this group is for.",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.transitagency",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollmentgroup",
            name="enrollment_flow",
            field=models.ForeignKey(
                help_text="The enrollment flow that this group is for.",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.enrollmentflow",
            ),
        ),
        migrations.RunPython(migrate_data),
    ]
