# Generated by Django 5.2.17 on 2026-09-04 18:29

import django.db.models.deletion
from django.db import migrations, models

import benefits.core.models.common
import benefits.secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitConfig",
            fields=[
                (
                    "transitprocessorconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.transitprocessorconfig",
                    ),
                ),
                (
                    "tokenization_api_key",
                    models.CharField(blank=True, default="", help_text="The Collect.js API key used for tokenization."),
                ),
                (
                    "registration_base_url",
                    models.URLField(
                        blank=True, default="", help_text="The absolute base url of the MOBILEvario API instance."
                    ),
                ),
                (
                    "registration_username",
                    models.CharField(
                        blank=True, default="", help_text="The username used to authenticate with MOBILEvario.", max_length=50
                    ),
                ),
                (
                    "registration_password_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing the password used to authenticate with MOBILEvario, "
                        "typically: [agency]-init-registration-password",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name": "INIT Config",
            },
            bases=("core.transitprocessorconfig",),
        ),
    ]
