# Generated by Django 5.2.17 on 2026-08-27 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitConfig",
            fields=[
                (
                    "transitprocessorconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.transitprocessorconfig",
                    ),
                ),
                (
                    "tokenization_api_key",
                    models.TextField(
                        blank=True, default="", help_text="The API key used to access Collect.js for tokenization."
                    ),
                ),
            ],
            bases=("core.transitprocessorconfig",),
        ),
    ]
