# Generated by Django 5.2.17 on 2026-09-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
        ("enrollment_init", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.PositiveIntegerField(
                        blank=True, default=None, help_text="The ID of the INIT FareCategory for user enrollment."
                    ),
                ),
            ],
            options={
                "verbose_name": "INIT group",
            },
            bases=("core.enrollmentgroup",),
        ),
    ]
