# Generated by Django 5.2.17 on 2026-08-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_enrollmentflow_system_name"),
        ("enrollment_init", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.IntegerField(blank=True, default=None, help_text="The ID of the INIT group for user enrollment."),
                ),
            ],
            bases=("core.enrollmentgroup",),
        ),
    ]
