# Generated by Django 5.1.7 on 2025-05-05 19:07

import benefits.core.models.common
import benefits.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LittlepayConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment",
                    models.TextField(
                        choices=[("qa", "QA"), ("prod", "Production")],
                        help_text="A label to indicate which environment this configuration is for.",
                    ),
                ),
                (
                    "agency_slug",
                    models.SlugField(
                        choices=[("cst", "cst"), ("mst", "mst"), ("nevco", "nevco"), ("sacrt", "sacrt"), ("sbmtd", "sbmtd")],
                        help_text="A label to indicate which agency this configuration is for. Note: the field "
                        "that controls which configuration an agency actually uses is on the TransitAgency model.",
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's audience value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's client_id value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing this agency's client_secret value used to access "
                        "the TransitProcessor's API.",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
            ],
        ),
    ]
