# Generated by Django 5.1.7 on 2025-07-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_enrollmentgroup"),
        ("enrollment_littlepay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LittlepayGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.UUIDField(blank=True, default=None, help_text="The ID of the Littlepay group for user enrollment."),
                ),
            ],
            bases=("core.enrollmentgroup",),
        ),
    ]
