# Generated by Django 5.1.7 on 2025-07-12 03:28

from uuid import UUID

import django.db.models.deletion
from django.db import migrations, models


def migrate_littlepay_group_ids(apps, schema_editor):
    LittlepayGroup = apps.get_model("enrollment_littlepay", "LittlepayGroup")
    EnrollmentFlow = apps.get_model("core", "EnrollmentFlow")

    for flow in EnrollmentFlow.objects.all():
        group_id = flow.group_id
        if group_id:
            try:
                UUID(group_id, version=4)
            except ValueError as e:
                raise ValueError(f"Invalid group_id {group_id} on flow {flow}") from e

            littlepay_group = LittlepayGroup.objects.create(group_id=group_id, enrollment_flow=flow)
            littlepay_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_enrollmentgroup"),
        ("enrollment_littlepay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LittlepayGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.UUIDField(blank=True, default=None, help_text="The ID of the Littlepay group for user enrollment."),
                ),
            ],
            bases=("core.enrollmentgroup",),
        ),
        migrations.RunPython(migrate_littlepay_group_ids),
    ]
