# Generated by Django 5.2.17 on 2026-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_littlepay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="littlepayconfig",
            name="audience",
            field=models.CharField(
                blank=True, default="", help_text="This agency's audience value used to access the TransitProcessor's API."
            ),
        ),
        migrations.AlterField(
            model_name="littlepayconfig",
            name="client_id",
            field=models.CharField(
                blank=True, default="", help_text="This agency's client_id value used to access the TransitProcessor's API."
            ),
        ),
    ]
