# Generated by Django 5.1.7 on 2025-07-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_remove_enrollmentflow_group_id"),
        ("enrollment_littlepay", "0002_littlepaygroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LittlepayConfig",
            new_name="OldLittlepayConfig",
        ),
    ]
