# Generated by Django 5.1.7 on 2025-07-14 09:21

import benefits.core.models.common
import benefits.secrets
import django.db.models.deletion
from django.db import migrations, models


def migrate_littlepay_config(apps, schema_editor):
    OldLittlepayConfig = apps.get_model("enrollment_littlepay", "OldLittlepayConfig")
    LittlepayConfig = apps.get_model("enrollment_littlepay", "LittlepayConfig")

    for old_config in OldLittlepayConfig.objects.all():
        new_config = LittlepayConfig.objects.create(
            environment=old_config.environment,
            agency_slug=old_config.agency_slug,
            audience=old_config.audience,
            client_id=old_config.client_id,
            client_secret_name=old_config.client_secret_name,
        )

        if hasattr(old_config, "transitagency"):
            new_config.transit_agency = old_config.transitagency

        new_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_transitprocessorconfig"),
        ("enrollment_littlepay", "0003_rename_littlepayconfig_oldlittlepayconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="LittlepayConfig",
            fields=[
                (
                    "transitprocessorconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.transitprocessorconfig",
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's audience value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This agency's client_id value used to access the TransitProcessor's API.",
                    ),
                ),
                (
                    "client_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing this agency's client_secret value used to access the TransitProcessor's API.",  # noqa
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
            ],
            bases=("core.transitprocessorconfig",),
        ),
        migrations.RunPython(migrate_littlepay_config),
    ]
