# Generated by Django 5.1.7 on 2025-07-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_littlepay", "0004_littlepayconfig"),
        ("core", "0055_remove_transitagency_littlepay_config"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldLittlepayConfig",
        ),
        migrations.RenameModel(
            old_name="NewLittlepayConfig",
            new_name="LittlepayConfig",
        ),
    ]
