name: New Release
description: Publish a new release of the Benefits app
title: Make a Release
labels:
  - release
body:
  - type: markdown
    attributes:
      value: |
        ## Prepare a new release

        Use the form below to prepare a new release of the Benefits app.

        Each release is coordinated by a **Release Manager**. The release manager may assign sub-tasks or ask for help
        as-needed, but is otherwise responsible for all aspects of the release.

        After this issue is created, use the checklist to manage the steps
        of the release process, marking items as completed. [Read more about the
        release process](https://docs.calitp.org/benefits/deployment/release/).

        Close this issue when the checklist is complete.
    validations:
      required: true
  - type: input
    id: manager
    attributes:
      label: Release manager
      description: GitHub handle of who is responsible for this release; assign this issue to this user
      placeholder: "@cal-itp-bot"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: Calver-formatted version for this release
      placeholder: YYYY.0M.R
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Release type

        Reference the diagram and discussion on [the release process docs](https://docs.calitp.org/benefits/deployment/release/).

        * `Regular` release: propogates from `dev` to `test`, and then `test` to `prod`. Only possible if `dev` is ready to deploy.
        * `Hotfix` release: propogates from `test` to `prod`, skipping `dev`.
  - type: dropdown
    id: type
    attributes:
      label: What type of release is this?
      options:
        - "Regular"
        - "Hotfix"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Release checklist

        After this issue is created, edit the description to keep only the checklist for the release type.
  - type: checkboxes
    id: regular-checklist
    attributes:
      label: Regular release checklist
      description: Complete these items in sequence as the `Regular` release progresses
      options:
        - label: Ensure the `dev` branch and secrets are up to date
        - label: Create a branch called release/version from the source branch
        - label: Bump the application version
        - label: Open a PR for the release branch into `dev`, merge
        - label: Ensure `test` secrets are up to date
        - label: Open another PR from `dev` to `test`, merge
        - label: QA the app in test
        - label: Ensure `prod` secrets are up to date
        - label: Open a PR for the `test` branch into `prod`, merge
        - label: QA the app in prod
        - label: Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
        - label: Create a release in GitHub for the tag, generating release notes
        - label: Edit release notes with additional context, images, animations, etc. as-needed
  - type: checkboxes
    id: hotfix-checklist
    attributes:
      label: Hotfix release checklist
      description: Complete these items in sequence as the `Hotfix` release progresses
      options:
        - label: Make the hotfix in a branch from `prod`
        - label: Bump the application version
        - label: Ensure `prod` secrets are up to date
        - label: Open a PR from the hotfix branch into `prod`, merge
        - label: QA the fix in prod
        - label: Tag the release on `prod`, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
        - label: Create a release in GitHub for the tag, generating release notes
        - label: Edit release notes with additional context, images, animations, etc. as-needed
        - label: "**Apply hotfix to `dev`** (sub-steps below):"
        - label: Create a branch off `dev`
        - label: Open a PR from `prod` into that branch, merge
        - label: (optional) Adapt hotfix to current state of `dev` in that same branch
        - label: Merge the PR into `dev`
