# Generated by Django 5.2.11 on 2026-02-26 22:39
# This is a migration reset encompassing 5 prior migrations.
# flake8: noqa

import django.db.models.deletion
from django.db import migrations, models

import benefits.core.models.common
import benefits.secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchioGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.TextField(blank=True, default=None, help_text="The ID of the Switchio group for user enrollment."),
                ),
            ],
            bases=("core.enrollmentgroup",),
        ),
        migrations.CreateModel(
            name="SwitchioConfig",
            fields=[
                (
                    "transitprocessorconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.transitprocessorconfig",
                    ),
                ),
                (
                    "tokenization_api_key",
                    models.TextField(
                        blank=True, default="", help_text="The API key used to access the Switchio API for tokenization."
                    ),
                ),
                (
                    "tokenization_api_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing the api_secret value used to access the Switchio API for tokenization.",
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "enrollment_api_authorization_header",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The value to use for the 'Authorization' header when accessing the Switchio API for enrollment.",
                    ),
                ),
                (
                    "pto_id",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="The Public Transport Operator ID to use with the Switchio API for enrollment.",
                    ),
                ),
                (
                    "ca_certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The CA certificate chain for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The client certificate for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
                (
                    "private_key",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The private key for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
            ],
            bases=("core.transitprocessorconfig",),
        ),
    ]
