# Generated by Django 5.2.11 on 2026-04-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_switchio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switchiogroup",
            name="group_id",
        ),
    ]
