# Generated by Django 5.2.11 on 2026-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_switchio", "0002_remove_switchiogroup_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switchioconfig",
            name="ca_certificate",
        ),
        migrations.RemoveField(
            model_name="switchioconfig",
            name="client_certificate",
        ),
        migrations.RemoveField(
            model_name="switchioconfig",
            name="enrollment_api_authorization_header",
        ),
        migrations.RemoveField(
            model_name="switchioconfig",
            name="private_key",
        ),
    ]
