# Generated by Django 5.1.7 on 2025-07-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_remove_enrollmentflow_group_id"),
        ("enrollment_switchio", "0002_switchioconfig_enrollment_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchioGroup",
            fields=[
                (
                    "enrollmentgroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.enrollmentgroup",
                    ),
                ),
                (
                    "group_id",
                    models.TextField(blank=True, default=None, help_text="The ID of the Switchio group for user enrollment."),
                ),
            ],
            bases=("core.enrollmentgroup",),
        ),
    ]
