# Generated by Django 5.2.17 on 2026-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_switchio", "0003_remove_switchioconfig_global_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchioconfig",
            name="tokenization_api_key",
            field=models.CharField(
                blank=True, default="", help_text="The API key used to access the Switchio API for tokenization."
            ),
        ),
    ]
