# Generated by Django 5.1.7 on 2025-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_remove_transitagency_littlepay_config"),
        ("enrollment_switchio", "0003_switchiogroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SwitchioConfig",
            new_name="OldSwitchioConfig",
        ),
    ]
