# Generated by Django 5.1.7 on 2025-07-14 10:20

import django.db.models.deletion
from django.db import migrations, models

import benefits.core.models.common
import benefits.secrets


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_transitagency_switchio_config"),
        ("enrollment_switchio", "0004_rename_switchioconfig_oldswitchioconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchioConfig",
            fields=[
                (
                    "transitprocessorconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.transitprocessorconfig",
                    ),
                ),
                (
                    "tokenization_api_key",
                    models.TextField(
                        blank=True, default="", help_text="The API key used to access the Switchio API for tokenization."
                    ),
                ),
                (
                    "tokenization_api_secret_name",
                    benefits.core.models.common.SecretNameField(
                        blank=True,
                        default="",
                        help_text="The name of the secret containing the api_secret value used to access the Switchio API for tokenization.",  # noqa
                        max_length=127,
                        validators=[benefits.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "enrollment_api_authorization_header",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The value to use for the 'Authorization' header when accessing the Switchio API for enrollment.",  # noqa
                    ),
                ),
                (
                    "pto_id",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="The Public Transport Operator ID to use with the Switchio API for enrollment.",
                    ),
                ),
                (
                    "ca_certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The CA certificate chain for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The client certificate for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
                (
                    "private_key",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The private key for accessing the Switchio API.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.pemdata",
                    ),
                ),
            ],
            bases=("core.transitprocessorconfig",),
        ),
        migrations.DeleteModel(
            name="OldSwitchioConfig",
        ),
    ]
