FROM benefits_client:latest

USER root

RUN apt-get install -qq --no-install-recommends curl git jq ssh && \
    python -m pip install --upgrade pip && \
    pip install --no-cache-dir flake8 pre-commit

# install node.js
# see https://github.com/nodesource/distributions#installation-instructions

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -qq nodejs libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev \
                        libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

COPY docs/requirements.txt docs/requirements.txt
RUN pip install --no-cache-dir -r docs/requirements.txt
