name: Check for up-to-date Django migrations
on:
  pull_request:
    paths:
      - "benefits/**"
  push:
    paths:
      - "benefits/**"

jobs:
  check-makemigrations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - uses: actions/setup-python@v5
        with:
          python-version-file: .github/workflows/.python-version
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install Python dependencies
        run: pip install -e .[dev,test]

      - name: Run ./bin/makemigrations.sh
        run: |
          if ./bin/makemigrations.sh | grep -q 'No changes detected';
          then
             exit 0;
          else
             exit 1;
          fi
