name: Label deploys

on:
  pull_request:
    branches: [prod, test]
    types: [closed]

jobs:
  label-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: add-label
        uses: andymckay/labeler@master
        with:
          add-labels: "deployment"
