name: Label docker

on:
  pull_request:
    types: [opened]
    paths:
      - ".devcontainer/**"
      - ".dockerignore"
      - "compose.yml"
      - "Dockerfile"

jobs:
  label-actions:
    runs-on: ubuntu-latest
    steps:
      - name: add-label
        uses: andymckay/labeler@master
        with:
          add-labels: "docker"
