name: Pytest

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      parent_event:
        type: string
        required: true

jobs:
  pytest:
    runs-on: ubuntu-latest

    # 1. Define the Postgres service
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: django
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django_password
        ports:
          - 5432:5432
        # Wait until Postgres is healthy before running the job steps
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 2. Pass connection settings to your test step
    env:
      DJANGO_DB_PASSWORD: django_password
      POSTGRES_HOSTNAME: 127.0.0.1
      POSTGRES_SSLMODE: disable

    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action-data branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - uses: actions/setup-python@v7
        with:
          python-version-file: .github/workflows/.python-version
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install Python dependencies
        run: pip install -e .[test]

      - name: Run setup
        run: |
          python manage.py migrate
          python manage.py compilemessages
          python manage.py collectstatic --no-input

      - name: Run tests
        run: ./tests/pytest/run.sh

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: benefits/static/coverage

      - name: Coverage comment
        if: ${{ inputs.parent_event != 'workflow_dispatch' }}
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 80
